### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by siboles** [simupy/simupy#1]
Using

`pip install simupy`

with pip=9.0.1 in python 3.6
only creates simupy-0.1.0-py3.6.egg-info but no module directory.

`import simupy`

raises: 
ModuleNotFoundError: No module named 'simupy'

Installing the dev901 release works.

`pip install simupy==0.1.0.dev901`

Tested in both conda environment and root system python.

**Comment by sixpearls** [comment]
Thanks, I didn't realize that pypi didn't suggest versions with 4th order identifiers, so the 1.0.0.dev1 release candidate wasn't being pulled by pip install. I've uploaded version 0.2.0 to pypi as a release candidate which fixes this problem on my end. I will close it, but if you still have the problem I will re-open and debug further.
