### ISSUE TITLE
LTISystem(A,B,C,D)

### ISSUE THREAD

**Issue by mftatfcyclone** [simupy/simupy#12]
How to represent a linear time invariant system with A,B,C,D matrices ?
dx_dt = Ax + Bu
    y    = Cx + Du
 ```
sys=LTISystem(A,B,C,D)
Traceback (most recent call last):

  File "<ipython-input-99-af8b714e7c2f>", line 1, in <module>
    sys=LTISystem(A,B,C,D)

  File "D:\Anaconda3\lib\site-packages\simupy-1.0.0-py3.7.egg\simupy\systems\__init__.py", line 378, in __init__
    raise ValueError("LTI system expects 1, 2, or 3 args")

ValueError: LTI system expects 1, 2, or 3 args
```

**Comment by sixpearls** [comment]
Hi @mftatfcyclone, sorry for the delay in responding -- I just saw this issue. As indicated in the [docs](https://simupy.readthedocs.io/en/latest/math.html):

> SimuPy assumes systems have no direct feedthrough between inputs and outputs; this discpline avoids algebraic loops. You can simulate a system model that includes a feedthrough by augmenting the system. Augment the system using the input by including input components in the state and using derivatives of those signals in the control input. You can augment the system using the output by including the original output components in the state and using integrals of those signals in the system output.

The consequence of this modeling choice is that for LTI systems, you can have a system with state and three matrices (state matrix A, input matrix B, output matrix C) or a system with no state and single (gain or output) matrix. If your model with state requires a direct feedthrough from input to output, you can augment the system by incorporating the input as an additional state variable and replace the input with its derivative.

**Comment by FLSP** [comment]
@sixpearls Hi Ben, could you please give any example about how to make a feedthrough? I had a try by myself, but it seems not work at all.
