### ISSUE TITLE
Value error in bouncing ball example

### ISSUE THREAD

**Issue by aronfeher** [simupy/simupy#13]
Hello!

I was searching for an alternative to Simulink, to replace System theory lab works, and I've wound this nice framework. So far everything works fine, except the bouncing ball problem. The given example throws an error at the definition of the Switch system -- ValueError: Index not valide with an empty array -- which I suppose is caused by the Array([0]) parameter, but I have no idea how to overcome this error.

Any help would be appreciated.

With regards,
Áron Fehér.

**Comment by aronfeher** [comment]
Well the vanderpol.py and simple_saturation.py have the same errors in the system definitions.

**Comment by sixpearls** [comment]
Hi @aronfeher, what version of SimuPy are you using? I'm a bit behind in a new release, so currently the examples are broken if you install from PyPI. Have you tried installing from source?

Instructions:
In a command prompt, execute

```
pip uninstall simupy
```

to remove the current installation. Then, in a directory of your choice execute the following to download the development version and install:

```
git clone https://github.com/simupy/simupy.git
cd simupy
pip install -e setup.py
```

**Comment by aronfeher** [comment]
Hi! Thank you for the reply. I'm using the version 1.0.0, which is the same as the downloaded version.
I've uninstalled, and reinstalled from source, but the problem is still present. The SwitchedSystem(), and DynamicalSystem() functions raise the same error:
_Traceback (most recent call last):
  File "F:/Programming/PyCharm/Programs/SystemTheory/bouncing_ball.py", line 41, in <module>
    initial_condition=ic
  File "c:\users\csurleny\desktop\temp\simupy\simupy\discontinuities.py", line 78, in __init__
    DiscontinuousSystem.__init__(self, **kwargs)
  File "c:\users\csurleny\desktop\temp\simupy\simupy\systems\symbolic.py", line 70, in __init__
    self.state_equation = state_equation
  File "c:\users\csurleny\desktop\temp\simupy\simupy\systems\symbolic.py", line 123, in state_equation
    self.update_state_equation_function()
  File "c:\users\csurleny\desktop\temp\simupy\simupy\systems\symbolic.py", line 161, in update_state_equation_function
    if not self.dim_state or self.state_equation == empty_array():
  File "C:\Users\Csurleny\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\tensor\array\ndim_array.py", line 495, in __eq__
    return list(self) == list(other)
  File "C:\Users\Csurleny\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\tensor\array\ndim_array.py", line 460, in iterator
    yield self[()]
  File "C:\Users\Csurleny\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\tensor\array\dense_ndim_array.py", line 63, in __getitem__
    index = self._parse_index(index)
  File "C:\Users\Csurleny\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\tensor\array\ndim_array.py", line 76, in _parse_index
    raise ValueError("Index not valide with an empty array")
ValueError: Index not valide with an empty array_

**Comment by sixpearls** [comment]
What version of SymPy are you using? Actually, can you post the output of `pip list`?

**Comment by aronfeher** [comment]
Now that I'm looking at it it's version 1.5, but here's the whole post:

Package                           Version      
--------------------------------- -------------
absl-py                           0.1.10       
adafruit-ampy                     1.0.5        
apio                              0.4.0        
atomicwrites                      1.3.0        
attrs                             19.1.0       
backcall                          0.1.0        
beautifulsoup4                    4.6.0        
bleach                            1.5.0        
bs4                               0.0.1        
certifi                           2018.4.16    
chardet                           3.0.4        
click                             6.7          
colorama                          0.4.1        
control                           0.8.2        
cycler                            0.10.0       
Cython                            0.29.13      
decorator                         4.4.0        
defusedxml                        0.6.0        
ecdsa                             0.13         
entrypoints                       0.3          
esptool                           2.5.0        
filterpy                          1.4.5        
flang                             0.1.1        
Flask                             1.1.1        
Flask-Cors                        3.0.8        
freetype-py                       2.1.0.post1  
gekko                             0.2.3        
gitdb2                            2.0.5        
GitPython                         2.1.11       
gspread                           3.0.1        
hdlparse                          1.0.4        
helpdev                           0.6.10       
hidapi                            0.7.99.post21
html5lib                          0.9999999    
httplib2                          0.11.3       
idna                              2.7          
importlib-metadata                0.23         
intel-openmp                      2019.0       
intelhex                          2.2.1        
ipykernel                         5.1.2        
ipython                           7.8.0        
ipython-genutils                  0.2.0        
ipywidgets                        7.5.1        
itsdangerous                      1.1.0        
jedi                              0.15.1       
Jinja2                            2.10.1       
joblib                            0.13.2       
jsonmerge                         1.6.1        
jsonschema                        3.0.1        
jupyter                           1.0.0        
jupyter-client                    5.3.3        
jupyter-console                   6.0.0        
jupyter-contrib-core              0.3.3        
jupyter-contrib-nbextensions      0.5.1        
jupyter-core                      4.5.0        
jupyter-highlight-selected-word   0.2.0        
jupyter-latex-envs                1.4.6        
jupyter-nbextensions-configurator 0.4.1        
kiwisolver                        1.0.1        
lxml                              4.4.1        
Markdown                          2.6.11       
MarkupSafe                        1.1.1        
matplotlib                        2.2.2        
mistune                           0.8.4        
mkl                               2019.0       
more-itertools                    7.2.0        
mpmath                            1.1.0        
nbconvert                         5.6.0        
nbformat                          4.4.0        
netifaces                         0.10.9       
nose                              1.3.7        
notebook                          6.0.1        
numpy                             1.14.0       
oauth2client                      4.1.2        
opencv-contrib-python             4.0.0.21     
opencv-python                     3.4.1.15     
packaging                         19.0         
pandas                            0.24.2       
pandocfilters                     1.4.2        
parso                             0.5.1        
pickleshare                       0.7.5        
Pillow                            5.0.0        
pip                               19.3.1       
pluggy                            0.13.1       
prometheus-client                 0.7.1        
prompt-toolkit                    2.0.9        
protobuf                          3.5.1        
psutil                            5.6.3        
py                                1.8.0        
pyaes                             1.6.1        
pyasn1                            0.4.3        
pyasn1-modules                    0.2.2        
pycairo                           1.18.1       
pycwt                             0.3.0a22     
Pygments                          2.4.2        
PyJWT                             1.7.1        
PyOpenGL                          3.1.0        
pyparsing                         2.2.0        
PyQRCode                          1.2.1        
PyQt5                             5.13.0       
PyQt5-sip                         4.19.18      
PyQt5-stubs                       5.13.0.1     
pyqt5-tools                       5.13.0.1.5   
pyqtgraph                         0.10.0       
pyrsistent                        0.15.3       
pyserial                          3.4          
PySide2                           5.13.1       
pytest                            5.3.2        
python-dateutil                   2.7.3        
python-dotenv                     0.8.2        
pytz                              2018.3       
pyusb                             1.0.2        
PyWavelets                        0.5.2        
pywin32                           225          
pywinpty                          0.5.5        
pywinusb                          0.4.2        
PyYAML                            3.13         
pyzbar                            0.1.7        
pyzmq                             18.1.0       
QDarkStyle                        2.7          
qtconsole                         4.5.5        
requests                          2.19.1       
rsa                               3.4.2        
scikit-build                      0.10.0       
scikit-learn                      0.21.2       
scipy                             1.0.0        
semantic-version                  2.6.0        
Send2Trash                        1.5.0        
setuptools                        39.2.0       
shiboken2                         5.13.1       
simpy                             3.0.11       
sip                               4.19.7       
six                               1.11.0       
sklearn                           0.0          
slycot                            0.3.5.0      
smmap2                            2.0.5        
symbolator                        1.0.2        
sympy                             1.5          
tensorflow-gpu                    1.5.0        
tensorflow-tensorboard            1.5.1        
terminado                         0.8.2        
TerosHDL                          0.1.1        
testpath                          0.4.2        
tinyprog                          1.0.21       
tornado                           6.0.3        
tqdm                              4.32.1       
traitlets                         4.3.2        
UNKNOWN                           0.0.0        
urllib3                           1.22         
virtualenv                        16.1.0       
vispy                             0.6.1        
vunit-hdl                         4.0.8        
wcwidth                           0.1.7        
Werkzeug                          0.16.0       
wfdb                              2.2.1        
wheel                             0.30.0       
widgetsnbextension                3.5.1        
xunitgen                          1.0.3        
zipp                              0.6.0

**Comment by nosratullah** [comment]
I've got the same problem. here is my Simupy and Sympy version I installed so far:

sympy                  1.5
simupy                 1.0.0

**Comment by nosratullah** [comment]
Dear @aronfeher 
I've got the same problem. and it was because of the sympy version you are using.
Currently the Simupy framework has some issue working with Sympy (1.5) version.
To solve this issue try to replace an older version of Sympy by typing:
`pip install sympy==1.0`
the Simupy framework may has some problems with `matplotlib.pyplot` library as well.
you may need to save the plots by `plt.savefig("plot.png")` in order to see them.

**Comment by aronfeher** [comment]
Dear @nosratullah !
Thank you for the response. Replacing sympy 1.5 with sympy 1.0 solved the issue. So far I don't have problems with matplotlib, so everything is good.
