### ISSUE TITLE
PIP install bug: cumulative outputs error

### ISSUE THREAD

**Issue by jjuch** [simupy/simupy#14]
When inspecting the code in  the add_system() function in the BlockDiagram class, I noticed a bug. The added system's outputs are added twice to the cumulative output list:
```
 self.cum_outputs = np.append(self.cum_outputs,
              self.cum_outputs[-1] + system.dim_output)
 self.cum_outputs = np.append(self.cum_outputs,
              self.cum_outputs[-1] + system.dim_output)
```
I uninstalled simupy from my environment, using pip, to be sure that it wasn't because of me. After re-installing with pip, I got the same bug.

pip-version: 20.0.2

**Comment by sixpearls** [comment]
Thanks for trying out SimuPy! Unfortunately I am a bit behind on maintenance and releases. Would you mind installing from source? Instructions below.

In a command prompt, execute

```
pip uninstall simupy
```

to remove the current installation. Then, in a directory of your choice execute the following to download the development version and install:

```
git clone https://github.com/simupy/simupy.git
cd simupy
pip install -e setup.py
```

**Comment by jjuch** [comment]
Thanks for the fast response. I was able to follow the instructions until the last step. When installing with the editable, I get the following error:
```
ERROR: setup.py is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).
```
I tried using `pip install -e .`, which ran without errors and my code seems to work, but I don't know why this works, while the setup.py does not.

**Comment by sixpearls** [comment]
Thanks, @jjuch. I actually think `pip install -e <directory>` is the recommended way so I'm surprised my instructions worked in the past. Thanks for catching that.
