### ISSUE TITLE
Interactive plotting in examples is problematic

### ISSUE THREAD

**Issue by siboles** [simupy/simupy#2]
Using,
`plt.ion()`
results in rendered figures instantly closing using matlplotlib==2.0.2 in python 3.6.
Removing interactive plotting and calling
`plt.show()`
fixes the issue on my system.

**Comment by sixpearls** [comment]
Thanks. I forgot that interactive mode was not the most robust way to do this. I changed the examples to use ``plt.show()`` instead.
