### ISSUE TITLE
error in the pendulum example

### ISSUE THREAD

**Issue by nedima68** [simupy/simupy#3]
Hi,
I was trying to duplicate your presentation and I got and error when adding the damping effect to pendulum with the following code. There seems to be a mismatch in the state vector size and the input sizes.

from simupy.systems import LTISystem
sum1 = LTISystem(np.ones((1,5)))

BD = BlockDiagram(inertia, sum1, gravity, viscous_damping)
BD.connect(inertia, viscous_damping, outputs = [1])
BD.connect(sum1,inertia)
BD.connect(gravity, sum1, inputs = [0])
BD.connect(inertia, gravity, outputs = [0])
BD.connect(viscous_damping, sum1, inputs = [1])

plt.figure()
for bval in [0, 0.25, 0.5, 1.0]:
    parameters[b] = bval
    t= BD.simulate(8)
    plot_x(t,'viscous damping $b=$%d' % bval)
shape_figure()
plt.savefig('damped.pdf')

and I got the following error:.
I guess 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-02a87f962365> in <module>()
     12 for bval in [0, 0.25, 0.5, 1.0]:
     13     parameters[b] = bval
---> 14     t= BD.simulate(8)
     15     plot_x(t,'viscous damping $b=$%d' % bval)
     16 shape_figure()

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\simupy\block_diagram.py in simulate(self, tspan, integrator_class, integrator_options, event_finder, event_find_options)
    546             if sys.dim_input:
    547                 y0[output_start:output_end] = sys.output_equation_function(
--> 548                         t0, input_values).reshape(-1)
    549             else:
    550                 y0[output_start:output_end] = sys.output_equation_function(

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\simupy\systems\__init__.py in <lambda>(t, x)
    336             self.initial_condition = np.zeros(self.dim_state)
    337             self.output_equation_function = \
--> 338                 lambda t, x: (gain_matrix@x).reshape(-1)
    339             return
    340 

ValueError: shapes (1,5) and (2,) not aligned: 5 (dim 1) != 2 (dim 0)

**Comment by sixpearls** [comment]
Hi @nedima68,

Thanks for checking out SimuPy. You haven't provided the entire script you're running, specifically I'm not sure how the ``viscous_damping`` system you're adding to the ``BD`` is defined. Were you transcribing the code from the talk? I still need to do some house cleaning (merging some upstream changes to the code base and reviewing the examples) but I intend to put up the slides and example code soon.

Something like this should work. Could you try it and let me know if you still get an error?

```python
import numpy as np, sympy as sp
import matplotlib.pyplot as plt
from simupy.systems.symbolic import DynamicalSystem, dynamicsymbols
from simupy.block_diagram import BlockDiagram
from simupy.array import Array, r_

def plot_x(result, label=''):
    plt.plot(result.t, result.y[:,0]*180/np.pi, label=label)
    plt.xlabel('time, s')
    plt.ylabel('position, degrees')

x, v, u = dynamicsymbols('x v u')
l, m = sp.symbols('l m')

parameters = {l: 1, m: 1}

inertia = DynamicalSystem(
    state_equation = r_[v, u/(m*l**2)],
    state = r_[x,v],
    input_ = u,
    constants_values = parameters
)

g = sp.symbols('g')
parameters[g] = 9.8

gravity = DynamicalSystem(
    output_equation = -g*m*l*sp.sin(x),
    input_ = x,
    constants_values = parameters
)

b = sp.symbols('b')
parameters[b] = 1.0

viscous_damping = DynamicalSystem(
    output_equation = -b*v,
    input_ = v,
    constants_values = parameters
)

from simupy.systems import LTISystem
sum1 = LTISystem(np.ones((1,5)))


pendulum = BlockDiagram(inertia, sum1, gravity, viscous_damping)
pendulum.connect(inertia, viscous_damping, outputs=[1])
pendulum.connect(sum1, inertia)
pendulum.connect(gravity, sum1, inputs=[0])
pendulum.connect(inertia, gravity, outputs=[0])
pendulum.connect(viscous_damping, sum1, inputs=[1])

plt.figure()
for bval in [0, 0.25, 0.5, 1.0]:
    parameters[b] = bval
    plot_x(pendulum.simulate(8), 'viscous damping $b$=%d' % bval)
plt.tight_layout()
```

**Comment by nedima68** [comment]
Hi Ben,

Thanks a lot for the quick response. SimuPy looks quite useful and promising. Congrats for the effort.

I’ve tried the full script you have sent. İt gave me exactly the same error message I was getting. Which is the following.


---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-1-88be7d9eb042> in <module>()

     54 for bval in [0, 0.25, 0.5, 1.0]:

     55     parameters[b] = bval

---> 56     plot_x(pendulum.simulate(8), 'viscous damping $b$=%d' % bval)

     57 plt.tight_layout()



C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\simupy\block_diagram.py in simulate(self, tspan, integrator_class, integrator_options, event_finder, event_find_options)

    546             if sys.dim_input:

    547                 y0[output_start:output_end] = sys.output_equation_function(

--> 548                         t0, input_values).reshape(-1)

    549             else:

    550                 y0[output_start:output_end] = sys.output_equation_function(



C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\simupy\systems\__init__.py in <lambda>(t, x)

    336             self.initial_condition = np.zeros(self.dim_state)

    337             self.output_equation_function = \

--> 338                 lambda t, x: (gain_matrix@x).reshape(-1)

    339             return

    340



ValueError: shapes (1,5) and (2,) not aligned: 5 (dim 1) != 2 (dim 0)


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sixpearls** [comment]
Thanks @nedima68. I just pushed the latest development version up. If you install from the git repo it should run. Why don't you give it a try and let me know if it works on your machine.

**Comment by nedima68** [comment]
Hello Benjamin,

Thanks for the reply and the update. I tried to Access the git repo on https://github.com/simupy/simupy but it seems that there are no recent update on any baranch. I am not very familiar with github pull operation, so I might be doing something wrong. Could you please direct me to right direction here.
Best regards.
Nedim.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sixpearls** [comment]
In a command prompt, execute

```bash
pip uninstall simupy
```

to remove the current installation. Then, in a directory of your choice execute the following to download the development version and install:

```
git clone https://github.com/simupy/simupy.git
cd simupy
pip install -e setup.py
```

**Comment by nedima68** [comment]
Hello Benjamin,

That worked. Thanks a lot for all the support.

Take care, and best regards.
Nedim.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
