### ISSUE TITLE
Example with a PID controller

### ISSUE THREAD

**Issue by non-Jedi** [simupy/simupy#7]
I'm afraid I'm a simulink refugee without most of the mathematical
background to understand what it's doing under the covers (or I had
that background at one time before forgetting everything). Would it be
possible to include a simple example defining a PID controller with a
given gain (Kc), reset time (τI), and derivative time (τD)?

The ideal form of the controller equation (in time-domain) for
reference is:

```latex
$p(t) = \overline{p} + K_c(e(t) + \frac{1}{\tau_I} \int_0^t e(t)\,dt + \tau_D \frac{de(t)}{dt})$
```

![render](https://user-images.githubusercontent.com/17915621/63866928-08147280-c982-11e9-932b-23098fc7a8fd.png)

**Comment by non-Jedi** [comment]
Thanks! This would be great in the examples folder.

**Comment by sixpearls** [comment]
Added in 4d5d46e. Thanks for the suggestion.
