### ISSUE TITLE
Too stupid to figure it out

### ISSUE THREAD

**Issue by notthedoctor** [simupy/simupy#8]
I've been simulating a system just using odeint and spotted your project which should organize all the data handling which is a bit ugly in my case (everything is numerically indexed to try to save on indexing dictionaries in the differential function, urgh). I tried making just the inductor half of my system using simupy and I think I've tried most permutations of your example code and the code in the youtube video and I always run into an error message. The following is the point I just dropped it and walked away (unfortunately to use bms which it turns out doesn't actually support an ODE solver like odeint so the results are all off and runs slower than using odeint!), at the very least it might suggest where you could improve the documentation to make it easier to pick up. I'll probably swing back to simupy if you explain what I've done wrong but I really did burn a day just trying to do an inductor!.

Even if I couldn't figure it out it's still a great project btw.

```
from simupy.systems.symbolic import DynamicalSystem, dynamicsymbols
from simupy.block_diagram import BlockDiagram
from simupy.array import r_, Array
import sympy as sp
import numpy as np

u, i, f_s = dynamicsymbols('u i f_s')

L, R, f_f = sp.symbols('L R f_f')
params = {L:2e-3, R:1}

field = DynamicalSystem(
        state_equation = Array([u - i*R]),
        state = Array([f_s]),
        output_equation = Array([f_s]),
        input_ = Array([u, i]),
        constants_values = params)

inductance = DynamicalSystem(
        output_equation = f_s/L,
        input_ = f_s,
        constants_values = params)

BD = BlockDiagram(field, inductance)
BD.connect(field, inductance)
BD.connect(inductance, field, inputs=[1])
BD.simulate(10)
```

**Comment by sixpearls** [comment]
Hi @notthedoctor, could you let me know what governing equations you are trying to simulate? If I set an initial condition on your field, I get an exponential decay which could be consistent with an inductor:

```
field.initial_condition = np.array([1.])
res = BD.simulate(0.1)

fig, axes = plt.subplots(2, 1, constrained_layout=True, sharex=True)
for ax, y, sym in zip(axes, res.y.T, [f_s, i]):
    ax.plot(res.t, y)
    ax.set_ylabel('$%s$' % sp.latex(sym))
ax.set_xlabel('time')
plt.show()
```

![image](https://user-images.githubusercontent.com/1571853/66212654-29e4d180-e673-11e9-929d-52221b4aab33.png)

**Comment by sixpearls** [comment]
Also, could you let me know what error message you are getting and what version of SimuPy you are using? I am in-between releases, so the best thing to do would be to install from source.

Download or git clone the repository, wherever you want it to live then install it with ``pip install -e simupy``

**Comment by notthedoctor** [comment]
I'm simulating a DC motor, the state equations are below. I'll try with a download of the repo now.

```
def f(y, t, L, R, J, rotor_flux, fsrc, tstable):
    # State space
    # 0,1: f_s
    # 2: theta
    # 3: speed
    # 4: phase
    speed = y[3]
    [i, torque, u_s, dphase] = svToVars(y, t, L, rotor_flux, tstable)

    df_s = u_s - R*i
    dtheta = speed
    dspeed = torque/J
    return [df_s.real, df_s.imag, dtheta, dspeed, dphase]

def svToVars(y, t, L, rotor_flux, tstable):
    f_s = y[0] + 1j*y[1]
    theta = y[2]
    speed = y[3]    
    phase = y[4]
    f_f = rotor_flux*np.exp(1j*theta)
    
    f_m = f_s - f_f    
    i = f_m/L  
    torque = np.imag(np.conj(f_f)*i) - 0.2e-5*speed
    u_s = 24*np.exp(1j*phase)
    
    if t < tstable:
        #wdemand = 2*np.pi*fsrc*t/tstable
        wdemand = 2*np.pi*fsrc*(np.sin( np.pi*(t/tstable - 0.5) ) + 1)/2
    else:
        wdemand = 2*np.pi*fsrc
        
    return [i, torque, u_s, wdemand]

t = np.linspace(0, 2, 100001)
args = (2e-3, 1, 2e-6, 0.007, 400, 0.4)
sol = odeint(f, [0,0,0,0,0], t, args=args)
```

**Comment by sixpearls** [comment]
If you could provide the full example that was generating the error and the full error message, I can try to help debug. 

If you already have a numerical function for the state equations, you can use a standard (non-symbolic) ``DynamicalSystem`` object ([docs](https://simupy.readthedocs.io/en/latest/api/systems.html#simupy.systems.DynamicalSystem)). You muse provide a function with the signature `state_equation_function(t,x,u)` (`u` will be ommitted if `dim_input` is 0). If you do not provide an `output_equation_function`, it should default to outputting the state variables.

**Comment by notthedoctor** [comment]
Downloading the repo worked, thanks. I'll probably try moving the system over first thing Monday so I'll let you know how it goes.
All the best.

**Comment by sixpearls** [comment]
Great! I'll close the issue for now but feel free to comment again if you have issues and I can re-open it.
