### ISSUE TITLE
Question on my use-case

### ISSUE THREAD

**Issue by mvinyard** [simupy/simupy#9]
Hi,

I was wondering if you could help me with my use-case, especially as determining if this package is appropriate for what I would like to do. 

My goal is pretty simple: I want to simulate data given a set of ODEs
Ex:
```
x_dot = -x  + y^2
y_dot = -y - xy
```

Taken together, this set of equations should generate somewhat of a parabola. I would like to plot / visualize this data in 2-D - I understand here that I would need to set `dim_output(2)`. 

The part I am stuck on is how to add the extra variable (the dynamic_symbol, u in this case) in an appropriate manner such that the two equations can be in mutual terms (since originally, one is with respect to x and one with respect to y). I am not a mathematician, this is simply a step in an experiment I am setting up. That said, I would appreciate any guidance. 

Thanks!

**Comment by sixpearls** [comment]
You could do something like this:

```python

from simupy.block_diagram import BlockDiagram
from simupy.systems import DynamicalSystem
import numpy as np
import matplotlib.pyplot as plt

def state_equation(time, states,):
    x, y = states
    xdot = -x + y**2
    ydot = -y - x*y
    return np.array([xdot, ydot])

system = DynamicalSystem(state_equation, dim_state=2, dim_input=0)

blockdiagram = BlockDiagram(system)
system.initial_condition = np.array([1.0, 2.0])
result = blockdiagram.simulate(10)
```

Which simulates the system and puts the result in the `result` variable. We can plot the time-history,

```python
fig, ax = plt.subplots(1, 1, constrained_layout=True)
plt.plot(result.t, result.x[:, 0], label='x')
plt.plot(result.t, result.x[:, 1], label='y')
plt.xlabel('time, s')
plt.legend()
plt.grid()
```
![image](https://user-images.githubusercontent.com/1571853/67911167-d6b35100-fb42-11e9-8763-dbb819bc89c4.png)

and a phase portrait

```python
fig, ax = plt.subplots(1, 1, constrained_layout=True)
plt.plot(result.x[:, 0], result.x[:,1])
plt.grid()
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.axis('equal')
plt.show() 
```
![image](https://user-images.githubusercontent.com/1571853/67911189-f5194c80-fb42-11e9-9155-df6324f02dd2.png)


Hope this helps!

**Comment by mvinyard** [comment]
Thank you!

**Comment by sixpearls** [comment]
Hi,

In general, you need the same number of derivatives as states. In the state
equation function you gave, you only return two derivatives. If you want
you could also make z and b as paramters or the output of
sateless/memoryless systems.

Good luck!
Ben
